### ISSUE TITLE
First build fails

### ISSUE THREAD

**Issue by gdallasdye** [austin987/crawfishos#2]
I've attached a [terminal copy/paste here](https://gist.github.com/gdallasdye/a283c3c91ae6a308b34b7286bee53813). 

Build environment is a fresh Debian 10 Buster with dependencies (and qemu-user-static backport) installed. I think it may be due to the debootstrap changes.

**Comment by austin987** [comment]
It's not related to debootstrap, but rather https://github.com/austin987/crawfishos/commit/27e5299f64a8cd2b003f479cf53ff46cc3fcaee4

Looking at https://stackoverflow.com/questions/1417957/show-just-the-current-branch-in-git, you need git 2.22. Buster has 2.20: https://packages.debian.org/buster/git. git from buster-backports should work.
