### ISSUE TITLE
Can't update any packages

### ISSUE THREAD

**Issue by jvonhoff** [austin987/crawfishos#9]
I see that `sid.pref` is pinning all packages, so none will upgrade.  Is there a reason for this?  I can't install a newer Firefox, which was how I went down this rabbit hole, but as I am very new to Crawfish, and haven't been on Debian/Ubuntu in many years, I wasn't sure what the "Pin: release a=unstable" was.

Basically, will I just completely break everything (which is pretty great, by the way) if I un-pin, and let the system upgrade?

**Comment by austin987** [comment]
> I see that `sid.pref` is pinning all packages, so none will upgrade. Is there a reason for this?

This is from upstream (PrawnOS). I haven't looked at this in a while, so I can't give a good answer. From what I remember, there are custom versions of some x11/xfce/debian packages (iirc, keyboard settings, maybe some other stuff). The big thing to avoid upgrading would be the kernel, which requires particular care on chromebooks. AFAIK, other than that, you should be fine to upgrade packages (but of course, it's FOSS/without guarantee). I don't generally offer paid support, but it's important enough, reach out privately :p.

I can't install a newer Firefox, which was how I went down this rabbit hole, but as I am very new to Crawfish, and haven't been on Debian/Ubuntu in many years, I wasn't sure what the "Pin: release a=unstable" was.
> 
> Basically, will I just completely break everything (which is pretty great, by the way) if I un-pin, and let the system upgrade?

**Comment by jvonhoff** [comment]
Thanks for the reply -- I actually bit the bullet a few days ago & just removed that pin, and let the system upgrade normally.  I had some packages get swapped in for existing ones (this happens often in Arch -- replace libfoobar with libfoobar-1 and stuff like that) but so far nothing seems to be a problem.  Gnome starts up & seems to function normally.  I guess I was hoping for a bit more battery runtime from an ARM-linux chromebook, but otherwise, everything is working as it was before.

So, I can't speak for everyone, but in my case, I didn't see any ill effects from removing the pin & just letting the system upgrade. I'll close this issue.
